# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1381ceace86a85263fce5560f2e935d6b1e19b68d470c30e0691fa34cd99e914608ef542e572e6fb0e3d8f0131f79cddc7b959623e4028cd157eb55d68512a41

test:
  secret_key_base: c44165db8cec910e719e2bc6b2f37df96ef300527906a8ae390a4ff390d4f076875ec3d8237371cc7604126f83302049849b16fc6482a360875008a12dc9c2bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
